project:
  type: book

book:
  title: "MCC regression modeling with scpeakeR"
  subtitle: "Evaluating the dominant factor that drives agreement between CellChat and CellPhoneDB inference results across bioloigcal datasets"
  repo-url: https://github.com/nigelhojinker/scpeakeR

  author: "Nigel Ho"
  date: "3/13/2026"
  chapters:
    - index.qmd
    - NL.qmd
    - LS.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

