# Preface {.unnumbered}

CellChat and CellPhoneDB are two popular tools for analyzing cell-cell communication from single-cell RNA-seq data. Both tools contain a built-in prior knowledge of manually-curated HUMAN ligand-receptor interactions to infer potential communication between cell types based on their gene expression profiles. CellChat and CellPhoneDB adopt similar inference frameworks, where both packages explicitly account for heteromeric protein complexes, taking the expression of the complex to be zero the expression if any one subunit is zero. Additionally, both tools perform statistical analysis via permutation testing by random shuffling of cell type labels to determine the significance of inferred interactions. However, there are differences in the specific algorithms and parameters used by each tool, along with differences in their curated resource, despite containing overlapping interactions which may lead to differences in the inferred interactions. 

As such, we sought to isolate the factors contributing to the agreement between the two tools, along with their associated effect sizes, by comparing the inference results generated from both tools. To establish a baseline comparison, where both resources are minimally manipulated, we create a mapping table [`step1_map`](https://github.com/nigelhojinker/MCC_regression/blob/main/R/step1_map.R) that aligns interactions from both CellChat and CellPhoneDB resources after Database Harmonization Step 1. For more details on the database harmonization process adopted in scpeakeR, please refer to the link [here](https://webpages-nigelhojinkers-projects.vercel.app/).

In this book, we will compare the results generated by CellChat and CellPhoneDB across three distinct conditions:

- Method: CellChat or CellPhoneDB

- Mean Type: ThresholdedMean at 10% (t10), ThresholdedMean at 25% (t25) and triMean

- Database: CellChatDB (v2.2.0) or CellPhoneDB (v5.0.1)

This yields a total of 12 distinct configurations, which are compared in pairs, resulting in a contingency table as follows:


Due to the inherent sparsity of scRNA-seq datasets, where the expression of ligands and receptors in the data are zero, the number of interactions not significant in both results typically far exceed those in the other categories. We evaluate the factors contributing to the agreement between the two tools using the Matthew's Correlation Coefficient (MCC), which address this class imbalance in the inference results. 

